export type UserRole = 'admin' | 'supervisor' | 'technician';
export type UserStatus = 'active' | 'inactive';

export interface User {
  id: string;
  name: string;
  email: string;
  phone?: string;
  role: UserRole;
  status: UserStatus;
  createdAt: string;
  updatedAt: string;
}

export type AssetStatus = 'operational' | 'under_maintenance' | 'out_of_service' | 'retired';
export type AssetCategory = 'vehicle' | 'equipment' | 'machinery' | 'hvac' | 'electrical' | 'plumbing' | 'furniture' | 'it_equipment' | 'other';

export interface VehicleRenewal {
  lastRenewalDate: string;
  nextRenewalDate: string;
}

export interface Asset {
  id: string;
  name: string;
  assetCode: string;
  category: AssetCategory;
  status: AssetStatus;
  location: string;
  description?: string;
  manufacturer?: string;
  model?: string;
  serialNumber?: string;
  purchaseDate?: string;
  warrantyExpiry?: string;
  maintenanceIntervalDays?: number;
  lastMaintenanceDate?: string;
  nextMaintenanceDate?: string;
  riskScore?: number;
  riskLevel?: 'low' | 'medium' | 'high' | 'critical';
  qrCode?: string;
  imageUrl?: string;
  
  // Vehicle-specific fields
  isVehicle?: boolean;
  roadWorthiness?: VehicleRenewal;
  insurance?: VehicleRenewal;
  annualFee?: VehicleRenewal;
  
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  createdByName: string;
}

export type WorkOrderStatus = 'open' | 'assigned' | 'in_progress' | 'on_hold' | 'completed' | 'cancelled';
export type WorkOrderPriority = 'low' | 'medium' | 'high' | 'critical';
export type WorkOrderType = 'preventive' | 'corrective' | 'emergency' | 'inspection';

export interface WorkOrderPart {
  inventoryId: string;
  partName: string;
  quantity: number;
  unitCost: number;
  totalCost: number;
}

export interface WorkOrder {
  id: string;
  workOrderNumber: string;
  title: string;
  description: string;
  assetId: string;
  assetName: string;
  type: WorkOrderType;
  priority: WorkOrderPriority;
  status: WorkOrderStatus;
  assignedTo?: string;
  assignedToName?: string;
  createdBy: string;
  createdByName: string;
  dueDate?: string;
  estimatedHours?: number;
  actualHours?: number;
  partsUsed?: WorkOrderPart[];
  cost?: number;
  completionNotes?: string;
  isAutoGenerated: boolean;
  startedAt?: string;
  completedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export type InventoryStatus = 'in_stock' | 'low_stock' | 'out_of_stock';

export interface InventoryItem {
  id: string;
  name: string;
  partNumber?: string;
  category: string;
  description?: string;
  quantity: number;
  minThreshold: number;
  unitCost: number;
  supplier?: string;
  supplierContact?: string;
  location?: string;
  status: InventoryStatus;
  createdAt: string;
  updatedAt: string;
}

export interface InventoryLog {
  id: string;
  inventoryId: string;
  itemName: string;
  type: 'in' | 'out';
  quantity: number;
  reason: string;
  workOrderId?: string;
  workOrderNumber?: string;
  performedBy: string;
  performedByName: string;
  createdAt: string;
}

export interface Notification {
  id: string;
  userId: string;
  title: string;
  message: string;
  type: 'work_order' | 'inventory' | 'asset' | 'system';
  read: boolean;
  link?: string;
  createdAt: string;
}

export interface DashboardStats {
  totalAssets: number;
  operationalAssets: number;
  underMaintenanceAssets: number;
  outOfServiceAssets: number;
  highRiskAssets: number;
  totalWorkOrders: number;
  openWorkOrders: number;
  inProgressWorkOrders: number;
  completedWorkOrders: number;
  overdueWorkOrders: number;
  totalInventoryItems: number;
  lowStockItems: number;
  outOfStockItems: number;
  inventoryValue: number;
}
